---
# tasks file for netzwirt.graphite-cluster


- name: write config for graphite vhost
  template:
    dest: "/etc/apache2/{{ item }}"
    src: "etc/apache2/{{ item }}.j2"
  with_items:
  - sites-available/graphite.conf
  - conf-available/graphite-port.conf
  notify:
  - restart apache2
  

- name: enable graphite site
  command: "a2ensite graphite"
  register: _enable_graphite_site
  changed_when: "not 'already enabled' in _enable_graphite_site.stdout"
  notify:
  - restart apache2
  

- name: enable graphite conf
  command: "a2enconf graphite-port"
  register: _enable_graphite_port
  changed_when: "not 'already enabled' in _enable_graphite_port.stdout"
  notify:
  - restart apache2


